<a href="https://colab.research.google.com/github/RevazRevazashvili/data-science-bootcamp/blob/main/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
print(arr2d[:,2:])

[[3]
 [6]
 [9]]


In [28]:
print(arr2d[1:2,1:])

[[5 6]]
